# Generated by Django 5.0.2 on 2024-04-22 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
