# Generated by Django 5.0.2 on 2024-04-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_teacher_friend_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='followe_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_follow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='followers_list',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(null=True, upload_to='university_img'),
        ),
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='post_views',
            field=models.IntegerField(default=0, help_text='Number of post views for the university'),
        ),
        migrations.AddField(
            model_name='university',
            name='profile_views',
            field=models.IntegerField(default=0, help_text='Number of profile views for the university'),
        ),
        migrations.AddField(
            model_name='university',
            name='recent_visits',
            field=models.ManyToManyField(blank=True, related_name='recently_visited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='rule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_bg_img',
            field=models.ImageField(null=True, upload_to='university_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_bg_img',
            field=models.ImageField(null=True, upload_to='teacher_img'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_img',
            field=models.ImageField(null=True, upload_to='teacher_img'),
        ),
    ]
