# Generated by Django 5.0.2 on 2024-04-27 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_followrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='friends_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_bg_img',
            field=models.ImageField(null=True, upload_to='student_img'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_img',
            field=models.ImageField(null=True, upload_to='student_img'),
        ),
    ]
