# Generated by Django 5.0.2 on 2024-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_teacher_post_views_teacher_profile_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapp',
            old_name='application_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobapp',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
