# Generated by Django 5.0.2 on 2024-05-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_application_text_jobapp_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
