# Generated by Django 5.0.2 on 2024-05-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_img'),
        ),
    ]
