# Generated by Django 5.0.2 on 2024-05-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_teacher_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_img',
            field=models.ImageField(null=True, upload_to='teacher_img'),
        ),
    ]
