# Generated by Django 5.0.2 on 2024-05-04 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_teacher_user_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='recent_visits',
            field=models.ManyToManyField(blank=True, related_name='recently_visited_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
