# Generated by Django 5.0.4 on 2024-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
