# Generated by Django 5.0.4 on 2024-05-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_comment_post_alter_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
