# Generated by Django 5.0.2 on 2024-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_alter_skill_options_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualitative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
