# Generated by Django 5.0.2 on 2024-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_teacher_experience_teacher_qualitative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='experience_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='qualitative_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='jobapp_required_skills', to='API.skill'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='subject_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
